sudo: false
language: node_js
os:
  - linux
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - "10"
before_script:
  - npm prune
script:
  - npm run build
branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/
    - next
    - gh-page
    after_success:
  - npm run release